---
title: Tijd sinds start
hero_image: images/banner.png
description: Krijg de tijd sinds het begin van de scène
version: 4
listed: false
copyedit: false
last_tested: "2021-12-02"
steps:
  - title: Tijd sinds start

